language: go

go:
  - 1.4

install:
  - export GOPATH="$HOME/gopath"
  - mkdir -p "$GOPATH/src/google.golang.org"
  - mv "$TRAVIS_BUILD_DIR" "$GOPATH/src/google.golang.org/grpc"
  - go get -v -t -d google.golang.org/grpc/...

script:
  - go test -v google.golang.org/grpc/...
  - go test -v -race google.golang.org/grpc/...
